# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

##   Generated via the command line invocation:
##	 swig -c++ -o libABC.cpp -r library.i


#                         srun.swg                            #
#
# This is the basic code that is needed at run time within R to
# provide and define the relevant classes.  It is included
# automatically in the generated code by copying the contents of
# srun.swg into the newly created binding code.


# This could be provided as a separate run-time library but this
# approach allows the code to be included directly into the
# generated bindings and so removes the need to have and install an
# additional library.  We may however end up with multiple copies of
# this and some confusion at run-time as to which class to use. This
# is an issue when we use NAMESPACES as we may need to export certain
# classes.

######################################################################

if(length(getClassDef("RSWIGStruct")) == 0) 
  setClass("RSWIGStruct", representation("VIRTUAL"))



if(length(getClassDef("ExternalReference")) == 0) 
# Should be virtual but this means it loses its slots currently
#representation("VIRTUAL")
  setClass("ExternalReference", representation( ref = "externalptr"))



if(length(getClassDef("NativeRoutinePointer")) == 0) 
  setClass("NativeRoutinePointer", 
              representation(parameterTypes = "character",
                             returnType = "character",
                             "VIRTUAL"), 
              contains = "ExternalReference")

if(length(getClassDef("CRoutinePointer")) == 0) 
  setClass("CRoutinePointer", contains = "NativeRoutinePointer")


if(length(getClassDef("EnumerationValue")) == 0) 
  setClass("EnumerationValue", contains = "integer")


if(!isGeneric("copyToR")) 
 setGeneric("copyToR",
            function(value, obj = new(gsub("Ref$", "", class(value)))) 
               standardGeneric("copyToR"
           ))

setGeneric("delete", function(obj) standardGeneric("delete"))


SWIG_createNewRef = 
function(className, ..., append = TRUE)
{
  f = get(paste("new", className, sep = "_"), mode = "function")

  f(...)
}

if(!isGeneric("copyToC")) 
 setGeneric("copyToC", 
             function(value, obj = SWIG_createNewRef(class(value)))
              standardGeneric("copyToC"
            ))


# 
defineEnumeration =
function(name, .values, where = topenv(parent.frame()), suffix = "Value")
{
   # Mirror the class definitions via the E analogous to .__C__
  defName = paste(".__E__", name, sep = "")
  delayedAssign(defName,  .values, assign.env = where)

  if(nchar(suffix))
    name = paste(name, suffix, sep = "")

  setClass(name, contains = "EnumerationValue", where = where)
}

enumToInteger <- function(name,type)
{
   if (is.character(name)) {
   ans <- as.integer(get(paste(".__E__", type, sep = ""))[name])
   if (is.na(ans)) {warning("enum not found ", name, " ", type)}
   ans
   } 
}

enumFromInteger =
function(i,type)
{
  itemlist <- get(paste(".__E__", type, sep=""))
  names(itemlist)[match(i, itemlist)]
}

coerceIfNotSubclass =
function(obj, type) 
{
    if(!is(obj, type)) {as(obj, type)} else obj
}


setClass("SWIGArray", representation(dims = "integer"), contains = "ExternalReference")

setMethod("length", "SWIGArray", function(x) x@dims[1])


defineEnumeration("SCopyReferences",
                   .values = c( "FALSE" = 0, "TRUE" = 1, "DEEP" = 2))

assert = 
function(condition, message = "")
{
  if(!condition)
    stop(message)

  TRUE
}


if(FALSE) {
print.SWIGFunction =
function(x, ...)
 {
 }
}


#######################################################################

R_SWIG_getCallbackFunctionStack =
function()
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_debug_getCallbackFunctionData")
}

R_SWIG_addCallbackFunctionStack =
function(fun, userData = NULL)
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_R_pushCallbackFunctionData", fun, userData)
}


#######################################################################



setClass('C++Reference', contains = 'ExternalReference')
setClass('_p_ABC', contains = 'C++Reference')



setMethod('[', "ExternalReference",
function(x,i,j, ..., drop=TRUE) 
if (!is.null(x$"__getitem__")) 
sapply(i, function(n) x$"__getitem__"(i=as.integer(n-1))))

setMethod('[<-' , "ExternalReference",
function(x,i,j, ..., value) 
if (!is.null(x$"__setitem__")) {
sapply(1:length(i), function(n) 
x$"__setitem__"(i=as.integer(i[n]-1), x=value[n]))
x
})

setAs('ExternalReference', 'character',
function(from) {if (!is.null(from$"__str__")) from$"__str__"()})

suppressMessages(suppressWarnings(setMethod('print', 'ExternalReference',
function(x) {print(as(x, "character"))})))

# Start of new_ABC

`ABC` = function()
{
  ;ans = .Call('R_swig_new_ABC', PACKAGE='libABC');
  ans <- if (is.null(ans)) ans
  else new("_p_ABC", ref=ans);
  
  reg.finalizer(ans@ref, delete_ABC)
  ans
  
}

attr(`ABC`, 'returnType') = '_p_ABC'
class(`ABC`) = c("SWIGFunction", class('ABC'))

# Start of delete_ABC

`delete_ABC` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_delete_ABC', self, PACKAGE='libABC');
  
}

attr(`delete_ABC`, 'returnType') = 'void'
attr(`delete_ABC`, "inputTypes") = c('_p_ABC')
class(`delete_ABC`) = c("SWIGFunction", class('delete_ABC'))

# Start of ABC_GetValues

`ABC_GetValues` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_ABC_GetValues', self, as.logical(.copy), PACKAGE='libABC');
  
}

attr(`ABC_GetValues`, 'returnType') = 'numeric'
attr(`ABC_GetValues`, "inputTypes") = c('_p_ABC')
class(`ABC_GetValues`) = c("SWIGFunction", class('ABC_GetValues'))

# Start of ABC_GetName

`ABC_GetName` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_ABC_GetName', self, as.logical(.copy), PACKAGE='libABC');
  
}

attr(`ABC_GetName`, 'returnType') = 'character'
attr(`ABC_GetName`, "inputTypes") = c('_p_ABC')
class(`ABC_GetName`) = c("SWIGFunction", class('ABC_GetName'))

# Start of ABC_numObs_set

`ABC_numObs_set` = function(self, s_numObs)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_numObs = as.integer(s_numObs);
  
  if(length(s_numObs) > 1) {
    warning("using only the first element of s_numObs");
  };
  
  ;.Call('R_swig_ABC_numObs_set', self, s_numObs, PACKAGE='libABC');
  
}

attr(`ABC_numObs_set`, 'returnType') = 'void'
attr(`ABC_numObs_set`, "inputTypes") = c('_p_ABC', 'integer')
class(`ABC_numObs_set`) = c("SWIGFunction", class('ABC_numObs_set'))

# Start of ABC_numObs_get

`ABC_numObs_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_ABC_numObs_get', self, as.logical(.copy), PACKAGE='libABC');
  
}

attr(`ABC_numObs_get`, 'returnType') = 'integer'
attr(`ABC_numObs_get`, "inputTypes") = c('_p_ABC')
class(`ABC_numObs_get`) = c("SWIGFunction", class('ABC_numObs_get'))

# Start of accessor method for ABC
setMethod('$', '_p_ABC', function(x, name)

{
  accessorFuns = list('GetValues' = ABC_GetValues, 'GetName' = ABC_GetName, 'numObs' = ABC_numObs_get);
  vaccessors = c('numObs');
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  if (is.na(match(name, vaccessors))) function(...){
    f(x, ...)
  } else f(x);
}


);
# end of accessor method for ABC
# Start of accessor method for ABC
setMethod('$<-', '_p_ABC', function(x, name, value)

{
  accessorFuns = list('numObs' = ABC_numObs_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p_ABC', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('numObs' = ABC_numObs_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for ABC
setMethod('delete', '_p_ABC', function(obj) {delete_ABC(obj)})
# Start of MyFunction

`MyFunction` = function(.copy = FALSE)
{
  ;.Call('R_swig_MyFunction', as.logical(.copy), PACKAGE='libABC');
  
}

attr(`MyFunction`, 'returnType') = 'integer'
class(`MyFunction`) = c("SWIGFunction", class('MyFunction'))



